### ISSUE TITLE
hi. i am trying this only model code but,

### ISSUE THREAD

**Issue by bamtu** [tsugumi-sys/SA-ConvLSTM-Pytorch#22]
it always produces 

CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 821.06 MiB is free. Process 5543 has 13.94 GiB memory in use. Of the allocated memory 13.20 GiB is allocated by PyTorch, and 621.20 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

even if it is T4 or A100 colab GPU.

Thank you.

**Comment by tsugumi-sys** [comment]
@bamtu 
Thank you for reporting this issue :)
I'm checking now.

**Comment by bamtu** [comment]
hi. thanks for attention. 
it was not code error but my mistake for loading dataset.

thank you
