### ISSUE TITLE
i have a question. 

### ISSUE THREAD

**Issue by bamtu** [tsugumi-sys/SA-ConvLSTM-Pytorch#38]
hi. i have a question on your evaluation.

<img width="1177" alt="image" src="https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/assets/34215754/00414aca-37c0-46d2-9413-5331c2e72024">

this is a evaluation of the thing i created in my code using ConvLSTM, but your label 

![test-case0](https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/assets/34215754/9ab1faaf-06be-4369-922b-ca34c8c6fb14)

if you look at your work, label picture is different from mine, why?

thank you for your code fix and attention.

**Comment by tsugumi-sys** [comment]
@bamtu 
Thank you for your question :)
Do you refer to the different color scale between yours and mine?

**Comment by bamtu** [comment]
if it is because of different color scale, the labels are below. 
<img width="1176" alt="image" src="https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/assets/34215754/549685b7-5d41-4aa0-b30b-079a58c696d6">

so i want to know if it is train dataset distorted.
i checked that dataset(.npy) file is same.

thank you.

**Comment by tsugumi-sys** [comment]
@bamtu 
I see. The data in my figure is a dotted border.
I don't apply some preprocessing, so I think it is an image rendering problem.
I'm checking now
