### ISSUE TITLE
Runtime error with device issue

### ISSUE THREAD

**Issue by hw-kim-ivan** [tsugumi-sys/SA-ConvLSTM-Pytorch#8]
Dear tsugumi-sys,

While running the code, runtime error shows that all tensors are not on the same device as below.

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat)`

Since inputs and the model are seems to be passed to the GPU at the right moment by calling "constants.py" in each module,
what do you think the problem is about?

Thanks,
Ivan.

**Comment by tsugumi-sys** [comment]
@hw-kim-ivan 
I'm sorry for not getting back to you sooner.
I investigated this issue, but I couldn't reproduce it :(
