### ISSUE TITLE
How to train SA-ConvLSTM model with my own dataset?

### ISSUE THREAD

**Issue by MysteryNull** [tsugumi-sys/SA-ConvLSTM-Pytorch#88]
Hello! Thank for your work! Could you please tell me how to train SA-ConvLSTM model with my own dataset? I would be grateful if you could reply to me!

**Comment by tsugumi-sys** [comment]
@MysteryNull 
Sure :) How can I help you?

**Comment by MysteryNull** [comment]
> @MysteryNull Sure :) How can I help you?

My e-mail is 19822780956@163.com. And we may have a disscussion.Thank you.

**Comment by MysteryNull** [comment]
> @MysteryNull Sure :) How can I help you?
Excuse me, the data type I've created is similar to mnist_seq_test.npy, while you are using the built-in MOVING_MNIST dataset from torchvision.dataset. How can I convert the dataset?Thank you!

**Comment by tsugumi-sys** [comment]
@MysteryNull 
I see, could you upload and share your sample code?
Also, this code might be useful to you.
https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/blob/main/tests/utils.py

**Comment by MysteryNull** [comment]
> @MysteryNull I see, could you upload and share your sample code? Also, this code might be useful to you. https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/blob/main/tests/utils.py
I converted my image sequence into .npy files referencing this link “https://blog.csdn.net/souyan1991/article/details/115911546”, the shape of "mnist_seq_test.npy" is [20,10000,64,64], the first ten frames are used as input, and the next ten frames are used as targets. And the shape of my data is [8,2700,128,128], then I trained the model based on this link "https://github.com/sladewinter/ConvLSTM".

**Comment by tsugumi-sys** [comment]
@MysteryNull 

> And the shape of my data is [8,2700,128,128], then I trained the model based on this link "https://github.com/sladewinter/ConvLSTM".

I see, then you need to change `input_seq_length=1~7` and `frame_size=(128, 128)`.

https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/blob/7f27d4e0981235129c1ea3ca7997f38d82cf6e9f/examples/moving_mnist_self_attention_memory_convlstm.py#L16-L39

**Comment by tsugumi-sys** [comment]
And what task do you want to solve?
how many input frames do you use to predict next frames?
(In the above example, the model predicts the next 1 frame from the past 10 frames).

**Comment by MysteryNull** [comment]
> And what task do you want to solve? how many input frames do you use to predict next frames? (In the above example, the model predicts the next 1 frame from the past 10 frames).
I predict the next 1 frame from the past 4 frames.

**Comment by MysteryNull** [comment]
https://github.com/sladewinter/ConvLSTM/blob/master/Training.ipynb.
And this is the code the author created to generate the training dataset.
![Uploading 1.png…]()

**Comment by MysteryNull** [comment]
https://github.com/sladewinter/ConvLSTM/blob/master/Training.ipynb.
And this is the code the author created to generate the training dataset.
![1](https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/assets/91356383/373f05ad-89f7-445c-b2a0-762612437e22)

**Comment by tsugumi-sys** [comment]
@MysteryNull 

Sorry for late reply, here is a sample code :)
(I'm not checking it actually works but  it helps you understand how to apply your custom dataset)

```python
import torch
from torch import nn
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset

from core.constants import WeightsInitializer
from data_loaders.moving_mnist import VideoPredictionDataset
from pipelines.experimenter import Experimenter
from pipelines.trainer import TrainingParams
from pipelines.utils.early_stopping import EarlyStopping
from self_attention_memory_convlstm.seq2seq import SAMSeq2Seq, SAMSeq2SeqParams


class YourCustomDataset(Dataset):
    """
    args:
        data (torch.Tensor): your dataset
    """

    def __init__(self, data: torch.Tensor):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx: int) -> torch.Tensor:
        return self.data[idx]


class YourCustomDataLoader(DataLoader):
    def __init__(
        self,
        train_batch_size: int,
        shuffle: bool = True,
    ):
        self.train_batch_size = train_batch_size
        self.shuffle = shuffle

        # TODO: prepare your data and split into train, validation and test dataset.
        # You need to convert the original data to torch.Tensor and change chape from [8,2700,128,128] to [2700,8,1,128,128] (batch_size, frames, channel, height, width)
        data = torch.rand((100, 8, 1, 128, 128)).to(torch.float)
        train_data, valid_data, test_data = data[:60], data[60:80], data[80:]
        self.train_dataset = VideoPredictionDataset(
            train_data, input_frames=5, label_frames=1
        )
        self.train_dataset = VideoPredictionDataset(
            valid_data, input_frames=5, label_frames=1
        )
        self.train_dataset = VideoPredictionDataset(
            test_data, input_frames=5, label_frames=1
        )

    @property
    def train_dataloader(self) -> DataLoader:
        return DataLoader(
            self.train_dataset, batch_size=self.train_batch_size, shuffle=self.shuffle
        )

    @property
    def validation_dataloader(self) -> DataLoader:
        return DataLoader(self.valid_dataset, batch_size=1, shuffle=self.shuffle)

    @property
    def test_dataloader(self) -> DataLoader:
        return DataLoader(self.test_dataset, batch_size=1, shuffle=self.shuffle)


def main():
    ###
    # Common Params
    ###
    artifact_dir = "./tmp"
    input_seq_length = 10
    train_batch_size = 32
    ###
    # Setup Pipeline
    ###
    model_params: SAMSeq2SeqParams = {
        "attention_hidden_dims": 2,
        "input_seq_length": input_seq_length,
        "num_layers": 2,
        "num_kernels": 64,
        "return_sequences": False,
        "convlstm_params": {
            "in_channels": 1,
            "out_channels": 1,
            "kernel_size": (3, 3),
            "padding": "same",
            "activation": "relu",
            "frame_size": (64, 64),
            "weights_initializer": WeightsInitializer.He,
        },
    }

    model = SAMSeq2Seq(**model_params)

    training_params: TrainingParams = {
        "epochs": 1,
        "loss_criterion": nn.BCELoss(reduction="sum"),
        "accuracy_criterion": nn.L1Loss(),
        "optimizer": Adam(model.parameters(), lr=1e-4),
        "early_stopping": EarlyStopping(
            patience=30,
            verbose=True,
            delta=0.0001,
        ),
        "metrics_filename": "metrics.csv",
    }

    print("Loading dataset ...")
    data_loaders = YourCustomDataLoader(train_batch_size=train_batch_size)

    experimenter = Experimenter(artifact_dir, data_loaders, model, training_params)
    experimenter.run()


if __name__ == "__main__":
    main()
```

**Comment by MysteryNull** [comment]
I will try it. Thank you very much!
