### ISSUE TITLE
RuntimeError: Found dtype Byte but expected Float

### ISSUE THREAD

**Issue by houjanet** [tsugumi-sys/SA-ConvLSTM-Pytorch#9]
Dear tsugumi-sys,

While running the code, runtime error shows:
RuntimeError: Found dtype Byte but expected Float

When executing trainer.run() on line 94 of main.py, the aforementioned issue arises,
what do you think the problem is about?

Thanks,
Janet.

**Comment by tsugumi-sys** [comment]
@houjanet 
Dear janet

Thank you for reporting this issue :)
I'm checking now.
I suspect some package versions issue causes the problem.

**Comment by tsugumi-sys** [comment]
@houjanet 
Dear Janet
I think this issue has been fixed now :)
(I did some refactoring, and code architecture has changed)

Please check on your machine :)
