### ISSUE TITLE
How to use this model on graph network data sets such as METR-LA

### ISSUE THREAD

**Issue by SCUANA** [tsugumi-sys/SA-ConvLSTM-Pytorch#92]
I want to use SA-convLSTM model on the training graph network data set. How should I modify the code? (My email is 1469188141@qq.com, please communicate with me if it is convenient)

**Comment by tsugumi-sys** [comment]
@SCUANA 
Thank you for asking:)
I think SA-ConvLSTM is not suitable for graph data such as METR-LA, but it is for gridded data.
Do you have any related research?

**Comment by tsugumi-sys** [comment]
@SCUANA 
This research is interesting and maybe useful for you.
According to this paper, we can expand ConvLSTM for graph data, then I think we can also expand SA-ConvLSTM for graph data.
https://arxiv.org/abs/1902.09130


However, I cannot find any related research and sample code applying graph neural network for SA-ConvLSTM.

**Comment by tsugumi-sys** [comment]
@SCUANA 
I think it's a good idea that you try building graph convlstm first, then build graph sa-convlstm.
I don't understand much about GNN, so I cannot help you sorry :(

**Comment by tsugumi-sys** [comment]
I'm sorry but I'll close this issue because I cannot help anymore :(
